import { chromium } from "@playwright/test";
const SHOT = "/home/user/shots";
const browser = await chromium.launch({ args: ["--enable-unsafe-swiftshader"] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.addInitScript(() => { try { localStorage.setItem("farm_onboard", "1"); } catch {} });
await page.goto("http://localhost:3000", { waitUntil: "networkidle", timeout: 90_000 });
await page.locator("canvas").waitFor({ timeout: 30_000 });
await page.getByRole("button", { name: /آغاز|شروع|بازی/ }).first().tap();
await page.waitForTimeout(900);
const nameInput = page.locator("input").first();
await nameInput.tap({ timeout: 10_000 }).catch(() => {});
await nameInput.fill("امید").catch(() => {});
const gate = page.getByRole("button", { name: "آغاز داستان" });
if (await gate.count()) await gate.last().tap();
await page.waitForTimeout(600);
await page.evaluate(() => { const g = window.__game; const st = g.getState(); if (st?.story) { st.story.shown = false; g.setState(st); } });
await page.waitForTimeout(800);
await page.evaluate(() => window.__game.give(50000, 30000));
await page.waitForTimeout(600);
await page.evaluate(() => {
  const g = window.__game; const st = g.getState();
  const N = 36;
  const put = (x, y, b) => { st.tiles[y * N + x] = { k: "bld", v: 0.5, b, q: [], p: 0, out: [], autoMode: false }; };
  put(16, 14, "scarecrow"); put(18, 14, "seesaw"); put(20, 14, "haystack");
  put(16, 16, "lantern"); put(18, 16, "flower_arch"); put(20, 16, "rock_spring");
  const crop = (x, y, c, gg) => { st.tiles[y * N + x] = { k: "soil", v: 0.5, crop: c, g: gg, wet: true }; };
  crop(15, 18, "watermelon", 1); crop(17, 18, "watermelon", 0.5); crop(19, 18, "apple", 1); crop(21, 18, "cherry", 1); crop(23, 18, "mint", 1);
  g.setState(st);
});
await page.waitForTimeout(1200);
await page.screenshot({ path: `${SHOT}/v4-farm-new.png` });
await page.evaluate(() => window.__game.openPanel("decor"));
await page.waitForTimeout(900);
await page.screenshot({ path: `${SHOT}/v4-decor.png` });
await page.evaluate(() => window.__game.openPanel(null));
await page.waitForTimeout(400);
await page.getByRole("button", { name: "کاشت", exact: true }).tap();
await page.waitForTimeout(700);
await page.screenshot({ path: `${SHOT}/v4-seeds.png` });
console.log("v4 shots done");
await browser.close();
