import { chromium, devices } from "@playwright/test";
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices["Pixel 7"] });
const p = await ctx.newPage();
p.on("console", m => console.log("[console]", m.type(), m.text().slice(0,200)));
p.on("pageerror", e => console.log("[pageerror]", String(e).slice(0,300)));
p.on("response", r => { if (r.status() >= 400) console.log("[http]", r.status(), r.url()); });
await p.goto("http://127.0.0.1:3000/", { waitUntil: "networkidle" });
await p.waitForTimeout(3000);
console.log("canvas:", await p.locator("canvas").count(), "buttons:", await p.locator("button").count());
console.log("body:", (await p.locator("body").innerText()).slice(0,200).replace(/\n/g," | "));
await b.close();
