import { chromium, devices } from "@playwright/test";
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices["Pixel 7"] });
const p = await ctx.newPage();
p.on("console", m => console.log("[console]", m.type(), m.text().slice(0,160)));
p.on("pageerror", e => console.log("[pageerror]", String(e).slice(0,200)));
await p.goto("http://127.0.0.1:3000/", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /آغاز|شروع|بازی/ }).first().tap();
await p.waitForTimeout(1500);
await p.locator("input").first().fill("امید").catch(()=>{});
const g = p.getByRole("button", { name: "آغاز داستان" });
if (await g.count()) await g.last().tap().catch(()=>{});
await p.evaluate(() => { const w=window; const st=w.__game?.getState?.(); if (st?.story){ st.story.shown=false; w.__game.setState(st);} });
await p.waitForTimeout(800);
await p.evaluate(async () => { await window.__game?.save?.(); });
await p.waitForTimeout(600);
const info = await p.evaluate(() => {
  const raw = localStorage.getItem("farm_save");
  const d = JSON.parse(raw); d.savedAt = Date.now() - 120*60*1000;
  localStorage.setItem("farm_save", JSON.stringify(d));
  return { day: d.day, time: d.time, savedAt: d.savedAt, tiles: d.tiles.length };
});
console.log("seeded:", info);
await ctx.setOffline(true);
await p.reload({ waitUntil: "networkidle" });
await p.waitForTimeout(2500);
const after = await p.evaluate(() => {
  const st = window.__game?.getState?.();
  return { day: st?.day, time: Math.round(st?.time||0), coins: st?.coins, xp: st?.xp, ready: (st?.tiles||[]).filter(t=>t.crop && (t.g||0)>=1).length, started: localStorage.getItem("farm_started") };
});
console.log("after reload:", after);
console.log("has card:", await p.getByText("در غیاب شما").count());
console.log("body:", (await p.locator("body").innerText()).replace(/\n/g," | ").slice(0,300));
await b.close();
